# Generated by Django 5.0.7 on 2024-07-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
