# Generated by Django 5.0.7 on 2024-07-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='introduction',
            field=models.TextField(null=True),
        ),
    ]
