# Generated by Django 5.0.7 on 2024-08-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_remove_article_content_article_content_paragraph_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
